### ISSUE TITLE
When prairie installed in subdir links didn't work

### ISSUE THREAD

**Issue by kns** [OleKEH/prairie-openid2-server#6]
Because links looks like:
/login
/get_file.php

**Comment by OleKEH** [comment]
Hello, 
Prairie is meant to be installed in a subdomain either as a single user installation or as a multiuserinstallation with wildcard domain support. 
For single user: 
<subdomain>.basedomain.tld/ ( not in a folder below). This means that the openid identity will be just the that. 
Most ISP's have an option to create a subdomain of your basedomain, and just put all the code in that folder. 
Hope this helps. (remember the .htacces file that is needed for the rewrite rules). 
Ole
